#ifndef EVENTCONSTANTS_H_INCLUDED
#define EVENTCONSTANTS_H_INCLUDED

enum KeyPressSurfaces
{
    KEY_PRESS_SURFACE_DEFAULT,
    KEY_PRESS_SURFACE_UP,
    KEY_PRESS_SURFACE_DOWN,
    KEY_PRESS_SURFACE_LEFT,
    KEY_PRESS_SURFACE_RIGHT,
    KEY_PRESS_SURFACE_TOTAL
} ;



#endif // EVENTCONSTANTS_H_INCLUDED
